events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    charset utf-8;
    client_max_body_size 50M;
    error_log /var/log/nginx/error.log warn;

    server {
        listen 443 ssl;
        server_name _;  # (หรือจะใช้ localhost ก็ได้)

        ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Static
        location /static/ {
            alias /app/frontend/staticfiles/;
            autoindex off;
            expires 1d;
        }

        # Media (user upload)
        location /media/ {
            alias /app/frontend/media/;
            autoindex off;
            expires 1d;
        }

        # Proxy pass to Django (web)
        location / {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 600s;
            proxy_send_timeout 600s;
        }
    }

    server {
        listen 80;
        server_name _;
        client_max_body_size 50M;
        return 301 https://$host$request_uri;
    }
}
