# Generated by Django 5.1.6 on 2025-03-08 14:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=users.models.default_profile_image, null=True, upload_to=users.models.user_profile_picture_path),
        ),
    ]
