# Generated by Django 5.2.2 on 2025-06-10 06:36

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'ผู้ใช้ทั่วไป'), ('admin', 'แอดมิน')], default='user', max_length=20, verbose_name='สิทธิ์ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=users.models.default_profile_image, null=True, upload_to=users.models.user_profile_picture_path, verbose_name='รูปโปรไฟล์'),
        ),
    ]
