# Generated by Django 5.2.3 on 2025-06-27 07:57

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_role_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=users.models.default_profile_image, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='member', max_length=50),
        ),
    ]
