# Generated by Django 5.2.3 on 2025-07-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_last_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('online', 'ออนไลน์'), ('dnd', 'ไม่รบกวน'), ('invisible', 'ซ่อนตัว')], default='online', max_length=16),
        ),
    ]
